//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTP_Banca_Transilvania
{
    using System;

    
    public partial class OtpPasswordTable
    {
        public int IdPAssword { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string OTPPass { get; set; }
        public Nullable<System.DateTime> TimeGenerated { get; set; }

        public OtpPasswordTable(int idPAssword, int? customerID, string oTPPass, DateTime? timeGenerated)
        {
            IdPAssword = idPAssword;
            CustomerID = customerID;
            OTPPass = oTPPass;
            TimeGenerated = timeGenerated;
        }
    }
}
